# Generated by Django 4.2.4 on 2023-10-25 14:43

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apteka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=255)),
                ('jami_qoldiq', models.DecimalField(decimal_places=0, max_digits=14)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Apteka',
                'verbose_name_plural': 'Aptekalar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim_nomi', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bolim',
                'verbose_name_plural': 'Bolimlar',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('masul_shaxs', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='TovarYuborishFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar_summasi', models.DecimalField(decimal_places=0, max_digits=14)),
                ('from_filial', models.PositiveIntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('to_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nasiyachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('middle_name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('passport', models.CharField(max_length=22, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nasiyachi',
                'verbose_name_plural': 'Nasiyachilar',
            },
        ),
        migrations.CreateModel(
            name='Nasiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek_raqami', models.PositiveBigIntegerField()),
                ('nasiya_summasi', models.DecimalField(decimal_places=0, max_digits=14)),
                ('tolangan_summalar', models.JSONField(default=list, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('tolov_muddati', models.DateField()),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nasiyachi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.nasiyachi')),
            ],
            options={
                'verbose_name': 'Nasiya',
                'verbose_name_plural': 'Nasiyalar',
            },
        ),
        migrations.CreateModel(
            name='KunlikSavdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naqd_pul', models.DecimalField(decimal_places=0, max_digits=14)),
                ('terminal', models.DecimalField(decimal_places=0, max_digits=14)),
                ('card_to_card', models.DecimalField(decimal_places=0, max_digits=14)),
                ('inkassa', models.DecimalField(decimal_places=0, max_digits=14)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik savdo',
                'verbose_name_plural': 'Kunlik savdolar',
            },
        ),
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('middle_name', models.CharField(max_length=155)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hodim',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='HisoblanganOylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik', models.DecimalField(decimal_places=0, max_digits=14)),
                ('oylik_tarixi', models.JSONField(default=dict)),
                ('hodim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dorixona_app.hodim')),
            ],
            options={
                'verbose_name': 'Hisoblanganoylik',
                'verbose_name_plural': 'Hisoblanganoyliklar',
            },
        ),
        migrations.CreateModel(
            name='Harajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naqd_pul', models.DecimalField(decimal_places=0, max_digits=14)),
                ('plastik', models.DecimalField(decimal_places=0, max_digits=14)),
                ('izoh', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hodim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.hodim')),
            ],
            options={
                'verbose_name': 'Harajat',
                'verbose_name_plural': 'Harajatlar',
            },
        ),
        migrations.CreateModel(
            name='FirmaSavdolari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_raqami', models.CharField(max_length=50)),
                ('harid_sanasi', models.DateTimeField(auto_now=True)),
                ('tolov_muddati', models.DateField()),
                ('tolangan_summalar', models.JSONField(default=list, null=True)),
                ('tan_narxi', models.DecimalField(decimal_places=0, max_digits=14)),
                ('sotish_narxi', models.DecimalField(decimal_places=0, max_digits=14)),
                ('qaytarilgan_tovar_summasi', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('ochirishga_sorov', models.BooleanField(default=False)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('firma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.firma')),
            ],
            options={
                'verbose_name': 'Firma savdosi',
                'verbose_name_plural': 'Firma savdolari',
            },
        ),
    ]
