# Generated by Django 4.2.4 on 2023-09-15 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apteka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=255)),
                ('jami_qoldiq', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apteka',
                'verbose_name_plural': 'Aptekalar',
            },
        ),
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim_nomi', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bolim',
                'verbose_name_plural': 'Bolimlar',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('qarz', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='Harajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harajat_summasi', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Harajat',
                'verbose_name_plural': 'Harajatlar',
            },
        ),
        migrations.CreateModel(
            name='KunlikSavdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_summa', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Kunliksavdo',
                'verbose_name_plural': 'Kunliksavdolar',
            },
        ),
        migrations.CreateModel(
            name='Nasiyachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('passport', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'Nasiyachi',
                'verbose_name_plural': 'Nasiyachilar',
            },
        ),
        migrations.CreateModel(
            name='Nasiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek_raqami', models.PositiveBigIntegerField()),
                ('savdo_summasi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tolangan_summa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qarz_holati', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('tolov_muddati', models.DateField()),
                ('tegishli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.nasiyachi')),
            ],
            options={
                'verbose_name': 'Nasiya',
                'verbose_name_plural': 'Nasiyalar',
            },
        ),
        migrations.CreateModel(
            name='HisoblanganOylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik', models.DecimalField(decimal_places=2, max_digits=11)),
                ('oylik_tarixi', models.JSONField(default=dict)),
                ('hodim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisoblanganoylik',
                'verbose_name_plural': 'Hisoblanganoyliklar',
            },
        ),
    ]
