# Generated by Django 4.2.4 on 2023-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasiya',
            name='qolgan_qarz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
