# Generated by Django 4.2.4 on 2023-10-25 14:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apteka',
            name='jami_qoldiq',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14),
        ),
    ]
