# Generated by Django 4.2.4 on 2023-09-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0002_nasiya_qolgan_qarz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasiya',
            name='qolgan_qarz',
        ),
    ]
