# Generated by Django 4.2.4 on 2023-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0003_remove_nasiya_qolgan_qarz'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasiyachi',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
