# Generated by Django 4.2.4 on 2023-10-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0003_alter_tovaryuborishfilial_from_filial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovaryuborishfilial',
            name='date',
        ),
        migrations.AlterField(
            model_name='tovaryuborishfilial',
            name='from_filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_tovar_filials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tovaryuborishfilial',
            name='to_filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_tovar_filials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tovaryuborishfilial',
            name='tovar_summasi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
