# Generated by Django 4.2.4 on 2023-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0004_nasiyachi_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasiyachi',
            name='middle_name',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
