# Generated by Django 4.2.4 on 2023-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0005_nasiyachi_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasiyachi',
            name='passport',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
