# Generated by Django 4.2.4 on 2023-10-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0005_alter_tovaryuborishfilial_to_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopshirilganPul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naqd_pul', models.DecimalField(decimal_places=0, max_digits=14)),
                ('card_to_card', models.DecimalField(decimal_places=0, max_digits=14)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
