# Generated by Django 4.2.4 on 2023-09-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0006_alter_nasiyachi_passport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nasiya',
            old_name='savdo_summasi',
            new_name='nasiya_summasi',
        ),
        migrations.RenameField(
            model_name='nasiya',
            old_name='tegishli',
            new_name='nasiyachi_id',
        ),
        migrations.RenameField(
            model_name='nasiya',
            old_name='qarz_holati',
            new_name='tolandi',
        ),
        migrations.AddField(
            model_name='nasiya',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
