# Generated by Django 4.2.4 on 2023-09-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0007_rename_savdo_summasi_nasiya_nasiya_summasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasiya',
            name='tolov_tarixi',
            field=models.JSONField(default=dict),
        ),
    ]
