# Generated by Django 4.2.4 on 2023-10-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0008_alter_topshirilganpul_card_to_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolim',
            old_name='bolim_nomi',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bolim',
            name='apteka_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolim',
            name='manzil',
            field=models.CharField(default=1, max_length=450),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolim',
            name='masul_shaxs',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolim',
            name='tel',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
