# Generated by Django 4.2.4 on 2023-10-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0009_rename_bolim_nomi_bolim_name_bolim_apteka_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolim',
            name='apteka_id',
        ),
    ]
