# Generated by Django 4.2.4 on 2023-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0009_remove_firma_qarz_firma_masul_shaxs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='yaqin_qaytarish_sanasi',
            new_name='eng_yaqin_tolov_sanasi',
        ),
        migrations.AddField(
            model_name='firma',
            name='tel',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
    ]
