# Generated by Django 4.2.4 on 2023-10-26 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0010_remove_bolim_apteka_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovaryuborishfilial',
            name='tovar_summasi',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='BolimgaDori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=0, max_digits=14)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bolim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.bolim')),
            ],
            options={
                'verbose_name': 'BolimgaDori',
                'verbose_name_plural': 'BolimgaDorilar',
            },
        ),
    ]
