# Generated by Django 4.2.4 on 2023-09-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0010_rename_yaqin_qaytarish_sanasi_firma_eng_yaqin_tolov_sanasi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='tel',
            new_name='phone',
        ),
    ]
