# Generated by Django 4.2.4 on 2023-11-01 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0011_alter_tovaryuborishfilial_tovar_summasi_bolimgadori'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovaryuborishfilial',
            name='accepted_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tovaryuborishfilial',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
