# Generated by Django 4.2.4 on 2023-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0011_rename_tel_firma_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmasavdolari',
            options={'verbose_name': 'Firma savdosi', 'verbose_name_plural': 'Firma savdolari'},
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='masul_shaxs',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
