# Generated by Django 4.2.4 on 2023-09-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0012_alter_firmasavdolari_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmasavdolari',
            name='tolangan_summalar',
            field=models.JSONField(default={'summa': []}, null=True),
        ),
    ]
