# Generated by Django 4.2.4 on 2023-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0012_tovaryuborishfilial_accepted_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshirilganpul',
            name='qabul_qilindi',
            field=models.BooleanField(default=False),
        ),
    ]
