# Generated by Django 4.2.4 on 2023-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0013_alter_firmasavdolari_tolangan_summalar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmasavdolari',
            name='masul_shaxs',
        ),
        migrations.AlterField(
            model_name='firmasavdolari',
            name='tolangan_summalar',
            field=models.JSONField(default=list, null=True),
        ),
    ]
