# Generated by Django 4.2.4 on 2023-11-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0014_rename_data_topshirilganpul_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasiya',
            name='time',
        ),
        migrations.AlterField(
            model_name='firmasavdolari',
            name='harid_sanasi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='harajat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nasiya',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nasiyachi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
