# Generated by Django 4.2.4 on 2023-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0014_remove_firmasavdolari_masul_shaxs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmasavdolari',
            name='tolandi',
            field=models.BooleanField(default=False),
        ),
    ]
