# Generated by Django 4.2.4 on 2023-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0015_remove_nasiya_time_alter_firmasavdolari_harid_sanasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovaryuborishfilial',
            name='accepted_time',
            field=models.DateTimeField(null=True),
        ),
    ]
