# Generated by Django 4.2.4 on 2023-09-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0015_firmasavdolari_tolandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmasavdolari',
            name='apteka_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.apteka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='shartnoma_raqami',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='sotish_narxi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='tan_narxi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apteka',
            name='jami_qoldiq',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='firmasavdolari',
            name='tovar_summasi',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='harajat',
            name='harajat_summasi',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='hisoblanganoylik',
            name='oylik',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='kunliksavdo',
            name='jami_summa',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nasiya',
            name='nasiya_summasi',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nasiya',
            name='tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
