# Generated by Django 4.2.4 on 2023-09-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0016_firmasavdolari_apteka_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmasavdolari',
            name='tovar_summasi',
        ),
    ]
