# Generated by Django 4.2.4 on 2023-11-08 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0016_alter_tovaryuborishfilial_accepted_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='KirimDorilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kirim_summasi', models.DecimalField(decimal_places=0, max_digits=14)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apteka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
