# Generated by Django 4.2.4 on 2023-11-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0017_kirimdorilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunliksavdo',
            name='qabul_qildi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kunliksavdo',
            name='topshirdi',
            field=models.BooleanField(default=False),
        ),
    ]
