# Generated by Django 4.2.4 on 2023-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0017_remove_firmasavdolari_tovar_summasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmasavdolari',
            name='tolash_sanasi',
            field=models.DateTimeField(null=True),
        ),
    ]
