# Generated by Django 4.2.4 on 2023-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0018_firmasavdolari_tolash_sanasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmasavdolari',
            name='tolash_sanasi',
            field=models.DateField(null=True),
        ),
    ]
