# Generated by Django 4.2.4 on 2023-11-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0018_kunliksavdo_qabul_qildi_kunliksavdo_topshirdi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunliksavdo',
            name='topshirdi',
        ),
    ]
