# Generated by Django 4.2.4 on 2023-11-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0019_remove_kunliksavdo_topshirdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmasavdolari',
            name='tolangan_summalar',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='TopshirilganPul',
        ),
    ]
