# Generated by Django 4.2.4 on 2023-09-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0020_remove_firma_eng_yaqin_tolov_sanasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmasavdolari',
            old_name='tolash_sanasi',
            new_name='tolov_muddati',
        ),
    ]
