# Generated by Django 4.2.4 on 2023-09-17 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0021_rename_tolash_sanasi_firmasavdolari_tolov_muddati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmasavdolari',
            name='tolov_muddati',
            field=models.DateField(default=datetime.datetime(2023, 9, 17, 16, 35, 24, 752713, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
