# Generated by Django 4.2.4 on 2023-11-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0022_harajat_firma_uchun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisoblanganoylik',
            name='oylik',
        ),
        migrations.RemoveField(
            model_name='hisoblanganoylik',
            name='oylik_tarixi',
        ),
        migrations.AddField(
            model_name='hisoblanganoylik',
            name='ishlagan_kunlar',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hodim',
            name='ish_haqi_kunlik',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hodim',
            name='lavozimi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OlinganOylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=0, max_digits=14)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hodim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.hodim')),
            ],
        ),
    ]
