# Generated by Django 4.2.4 on 2023-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0023_remove_hisoblanganoylik_oylik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisoblanganoylik',
            name='date',
            field=models.DateField(default='2023-11-09'),
            preserve_default=False,
        ),
    ]
