# Generated by Django 4.2.4 on 2023-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0023_nasiya_apteka_id_nasiyachi_apteka_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasiya',
            name='tolangan_summa',
        ),
        migrations.RemoveField(
            model_name='nasiya',
            name='tolov_tarixi',
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='firmaga_qaytarildi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='izoh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='ochirishga_sorov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firmasavdolari',
            name='qaytarilgan_summa',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='nasiya',
            name='tolangan_summalar',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
