# Generated by Django 4.2.4 on 2023-11-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0024_hisoblanganoylik_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hisoblanganoylik',
            old_name='hodim',
            new_name='hodim_id',
        ),
    ]
