# Generated by Django 4.2.4 on 2023-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0024_remove_nasiya_tolangan_summa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apteka',
            name='jami_qoldiq',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='firmasavdolari',
            name='qaytarilgan_summa',
            field=models.DecimalField(decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='firmasavdolari',
            name='sotish_narxi',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='firmasavdolari',
            name='tan_narxi',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='harajat',
            name='harajat_summasi',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='hisoblanganoylik',
            name='oylik',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='kunliksavdo',
            name='jami_summa',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nasiya',
            name='nasiya_summasi',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
