# Generated by Django 4.2.4 on 2023-09-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0025_alter_apteka_jami_qoldiq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmasavdolari',
            old_name='qaytarilgan_summa',
            new_name='qaytarilgan_tovar_summasi',
        ),
    ]
