# Generated by Django 4.2.4 on 2023-09-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0026_rename_qaytarilgan_summa_firmasavdolari_qaytarilgan_tovar_summasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmasavdolari',
            name='firmaga_qaytarildi',
        ),
    ]
