# Generated by Django 4.2.4 on 2023-11-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0028_rename_summa_olinganoylik_card_to_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olinganoylik',
            name='card_to_card',
            field=models.DecimalField(decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='naqd_pul',
            field=models.DecimalField(decimal_places=0, max_digits=14, null=True),
        ),
    ]
