# Generated by Django 4.2.4 on 2023-09-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0028_remove_firmasavdolari_tolandi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmasavdolari',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
