# Generated by Django 4.2.4 on 2023-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0029_alter_firmasavdolari_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasiya',
            name='tolangan_summalar',
            field=models.JSONField(default=list, null=True),
        ),
    ]
