# Generated by Django 4.2.4 on 2023-11-19 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0029_alter_olinganoylik_card_to_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harajat',
            name='firma_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.firma'),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 10, 8, 21, 931226)),
        ),
    ]
