# Generated by Django 4.2.4 on 2023-12-12 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0030_harajat_firma_id_alter_olinganoylik_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasiya',
            name='chek_raqami',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='nasiya',
            name='tolangan_summalar',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 11, 17, 32, 272391)),
        ),
    ]
