# Generated by Django 4.2.4 on 2023-10-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0030_alter_nasiya_tolangan_summalar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasiya',
            name='tolandi',
        ),
    ]
