# Generated by Django 4.2.4 on 2023-12-12 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0031_alter_nasiya_chek_raqami_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nasiya',
            options={},
        ),
        migrations.AlterField(
            model_name='nasiya',
            name='nasiya_summasi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 11, 42, 8, 398661)),
        ),
    ]
