# Generated by Django 4.2.4 on 2023-10-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0031_remove_nasiya_tolandi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kunliksavdo',
            options={'verbose_name': 'Kunlik savdo', 'verbose_name_plural': 'Kunlik savdolar'},
        ),
        migrations.RenameField(
            model_name='kunliksavdo',
            old_name='jami_summa',
            new_name='card_to_card',
        ),
        migrations.AddField(
            model_name='kunliksavdo',
            name='inkassa',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kunliksavdo',
            name='naqd_pul',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kunliksavdo',
            name='terminal',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
