# Generated by Django 4.2.4 on 2023-10-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0032_alter_kunliksavdo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunliksavdo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
