# Generated by Django 4.2.4 on 2023-12-12 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0032_alter_nasiya_options_alter_nasiya_nasiya_summasi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nasiya',
            options={'verbose_name': 'Nasiya', 'verbose_name_plural': 'Nasiyalar'},
        ),
        migrations.AddField(
            model_name='nasiya',
            name='tolandi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nasiya',
            name='nasiya_summasi',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 16, 38, 30, 526981)),
        ),
    ]
