# Generated by Django 4.2.4 on 2023-10-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0033_alter_kunliksavdo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('middle_name', models.CharField(max_length=155)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='harajat',
            old_name='harajat_summasi',
            new_name='naqd_pul',
        ),
        migrations.AddField(
            model_name='harajat',
            name='izoh',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harajat',
            name='plastik',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harajat',
            name='hodim_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.hodim'),
            preserve_default=False,
        ),
    ]
