# Generated by Django 4.2.4 on 2023-12-12 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0033_alter_nasiya_options_nasiya_tolandi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 17, 2, 6, 63522)),
        ),
    ]
