# Generated by Django 4.2.4 on 2023-10-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0034_hodim_rename_harajat_summasi_harajat_naqd_pul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='apteka_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.apteka'),
            preserve_default=False,
        ),
    ]
