# Generated by Django 4.2.4 on 2023-12-21 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0034_alter_olinganoylik_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolimgadori',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 22, 56, 54, 880413)),
        ),
    ]
