# Generated by Django 4.2.4 on 2023-10-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0035_hodim_apteka_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hodim',
            options={'verbose_name': 'Hodim', 'verbose_name_plural': 'Hodimlar'},
        ),
        migrations.AddField(
            model_name='harajat',
            name='apteka_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.apteka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kunliksavdo',
            name='apteka_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.apteka'),
            preserve_default=False,
        ),
    ]
