# Generated by Django 4.2.4 on 2023-12-21 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0035_bolimgadori_accepted_alter_olinganoylik_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunliksavdo',
            old_name='qabul_qildi',
            new_name='accepted',
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 23, 0, 55, 27695)),
        ),
    ]
