# Generated by Django 4.2.4 on 2023-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0036_alter_hodim_options_harajat_apteka_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harajat',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kunliksavdo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
