# Generated by Django 4.2.4 on 2023-12-24 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0036_rename_qabul_qildi_kunliksavdo_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olinganoylik',
            name='card_to_card',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 23, 1, 28, 343443)),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='naqd_pul',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
