# Generated by Django 4.2.4 on 2023-10-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0037_alter_harajat_date_alter_kunliksavdo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarYuborishFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar_summasi', models.DecimalField(decimal_places=0, max_digits=14)),
                ('from_filial', models.PositiveIntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('to_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorixona_app.apteka')),
            ],
        ),
    ]
