# Generated by Django 4.2.4 on 2024-01-03 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorixona_app', '0038_alter_kunliksavdo_date_alter_olinganoylik_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmasavdolari',
            name='apteka_id',
        ),
        migrations.RemoveField(
            model_name='firmasavdolari',
            name='ochirishga_sorov',
        ),
        migrations.AlterField(
            model_name='kunliksavdo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 27, 10, 52762)),
        ),
        migrations.AlterField(
            model_name='olinganoylik',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 27, 10, 52762)),
        ),
    ]
